CREATE TABLE loan_application (
    application_id SERIAL PRIMARY KEY,
    borrower_id INT,
    full_name VARCHAR(150),
    email VARCHAR(255),
    mobile_no VARCHAR(20),
    dob DATE,
    gender VARCHAR(10),
    pan_no VARCHAR(10),
    aadhaar_no VARCHAR(14),
    address TEXT,
    pincode VARCHAR(6),
    city VARCHAR(100),
    state VARCHAR(100),
    residential_status VARCHAR(20),
    years_at_current_address INT,
    employment_type VARCHAR(50),
    bank_name VARCHAR(100),
    bank_account_no VARCHAR(20),
    ifsc_code VARCHAR(11),
    loan_amount DECIMAL(15,2),
    purpose_of_loan TEXT,
    loan_tenure INT,
    itr_url TEXT,
    bank_statement_url TEXT,
    status VARCHAR(20) DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (borrower_id) REFERENCES borrower(borrower_id) ON DELETE CASCADE
);

CREATE TABLE funded_loans (
    funded_loan_id SERIAL PRIMARY KEY,
    borrower_id INTEGER,
    lender_id INTEGER,
    funded_amount NUMERIC(15,2),
    interest_rate NUMERIC(5,2),
    loan_tenure INTEGER,
    start_date DATE DEFAULT CURRENT_DATE,
    end_date DATE,
    repayment_status VARCHAR(20) DEFAULT 'Active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (borrower_id) REFERENCES borrower(borrower_id) ON DELETE CASCADE,
    FOREIGN KEY (lender_id) REFERENCES lender(lender_id) ON DELETE CASCADE
);